<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageReference Include="Konfidence.BaseClasses" Version="2026.4.18" />
		<PackageReference Include="Konfidence.MsBuild" Version="2026.4.18" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ToolInterfaces\ToolInterfaces.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="ToolClasses.UnitTest" />
	</ItemGroup>

</Project>
