<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konfidence.BaseClasses" Version="2026.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToolInterfaces\ToolInterfaces.csproj" />
  </ItemGroup>

</Project>
