pool:
  name: Default

trigger: none

schedules:
- cron: "0 3 * * *"
  displayName: nightly build
  branches:
    include: 
    - develop
  always: true

resources:
  repositories:
    - repository: templates
      type: git
      name: Konfidence/yaml.Templates
      ref: refs/heads/main

variables:
  - name: solution
    value: '**/*.sln'
#- group: nuget.org-apikeys
#- name: NuGetApiKey
#  value: $[variables.NuGetApiKey]
  
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '$(solution)'
    feedsToUse: config
    nugetConfigPath: .nuget/NuGet.Config
    verbosityRestore: Normal

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'
    arguments: '-c $(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '$(solution)'
    arguments: '-c $(BuildConfiguration) --no-build  /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

- template: GenerateAndPublishCodeCoverage.yml@templates  

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '$(solution)'
    nobuild: true
    verbosityPack: Normal

- task: CopyFiles@2
  displayName: 'Copy Files to: \\konfidence8\publish'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    TargetFolder: '\\konfidence8\publish'

#- task: DotNetCoreCLI@2
#  displayName: 'dotnet publish nuget.org package'
#  inputs:
#    command: custom
#    custom: nuget
#    arguments: 'push $(Build.ArtifactStagingDirectory)\*.*nupkg -s https://api.nuget.org/v3/index.json -k $(NuGetApiKey) --skip-duplicate'
