<Project>
	<PropertyGroup>
		<Version>2026.4.1</Version>

		<Authors>Adrie Helmich.</Authors>
		<Copyright>Konfidence in it 2026.</Copyright>
		<Company>Konfidence in it</Company>
		<AssemblyCompany>Konfidence in it</AssemblyCompany>

		<IsPackable>false</IsPackable>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>

		<ComVisible>False</ComVisible>
		<CLSCompliant>False</CLSCompliant>
		<AssemblyCulture>en</AssemblyCulture>

		<PackageOutputPath>$(SolutionDir)nuget</PackageOutputPath>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/a3helmich/Konfidence.ProjectReferences</PackageProjectUrl>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<RepositoryUrl>https://github.com/a3helmich/Konfidence.ProjectReferences</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<IncludeSymbols>false</IncludeSymbols>
	</PropertyGroup>
	<ItemGroup>
		<None Include="$(SolutionDir)README.md" Pack="true" PackagePath="\"/>
	</ItemGroup>
</Project>
